import type { AgentEvent, MemoryNode, Track } from './types'

export const initialTracks: Track[] = [
  {
    id: 1,
    title: 'Slow Satellites',
    artist: 'Mira Vale',
    album: 'Soft Orbit',
    duration: '4:12',
    durationSeconds: 252,
    source: '网易云',
    quality: 'FLAC 16/44.1',
    cover: '/covers/soft-orbit.jpg',
    bpm: 82,
    musicalKey: 'F min',
    x: 11,
    y: 67,
    offline: true,
    verified: true,
    sizeMb: 28.6,
  },
  {
    id: 2,
    title: 'Glass Hours',
    artist: 'North Assembly',
    album: 'Afterimage',
    duration: '3:46',
    durationSeconds: 226,
    source: '酷我',
    quality: 'FLAC 24/44.1',
    cover: '/covers/glass-hours.jpg',
    bpm: 91,
    musicalKey: 'A min',
    x: 25,
    y: 56,
    offline: true,
    verified: true,
    sizeMb: 42.1,
  },
  {
    id: 3,
    title: 'Blue Static',
    artist: 'Lena Shore',
    album: 'Night Current',
    duration: '4:03',
    durationSeconds: 243,
    source: 'QQ',
    quality: 'FLAC 24/44.1',
    cover: '/covers/blue-static.jpg',
    bpm: 104,
    musicalKey: 'C maj',
    x: 42,
    y: 46,
    offline: false,
    verified: true,
    sizeMb: 45.8,
  },
  {
    id: 4,
    title: 'Second Wind',
    artist: 'Common Field',
    album: 'Open Late',
    duration: '3:31',
    durationSeconds: 211,
    source: '酷狗',
    quality: 'FLAC 16/44.1',
    cover: '/covers/second-wind.jpg',
    bpm: 116,
    musicalKey: 'D maj',
    x: 59,
    y: 33,
    offline: false,
    verified: true,
    sizeMb: 31.4,
  },
  {
    id: 5,
    title: 'Neon on the Water',
    artist: 'June Echo',
    album: 'After Midnight',
    duration: '4:28',
    durationSeconds: 268,
    source: 'QQ',
    quality: 'FLAC 24/44.1',
    cover: '/covers/neon-water.jpg',
    bpm: 124,
    musicalKey: 'E maj',
    x: 76,
    y: 20,
    offline: false,
    verified: true,
    sizeMb: 51.2,
  },
  {
    id: 6,
    title: 'Home Before Dawn',
    artist: 'Paper District',
    album: 'Last Train',
    duration: '3:58',
    durationSeconds: 238,
    source: '网易云',
    quality: 'FLAC 16/44.1',
    cover: '/covers/home-dawn.jpg',
    bpm: 108,
    musicalKey: 'B min',
    x: 89,
    y: 43,
    offline: false,
    verified: true,
    sizeMb: 34.7,
  },
]

export const searchCatalog: Track[] = [
  ...initialTracks,
  {
    id: 7,
    title: 'Afterglow Circuit',
    artist: 'Hana Loop',
    album: 'Soft Voltage',
    duration: '3:39',
    durationSeconds: 219,
    source: '网易云',
    quality: 'FLAC 24/48',
    cover: '/covers/neon-water.jpg',
    bpm: 112,
    musicalKey: 'G min',
    x: 14,
    y: 58,
    offline: false,
    verified: true,
    sizeMb: 43.2,
  },
  {
    id: 8,
    title: 'Quiet Machines',
    artist: 'Arlen Faye',
    album: 'Room Tone',
    duration: '4:41',
    durationSeconds: 281,
    source: 'QQ',
    quality: 'FLAC 16/44.1',
    cover: '/covers/soft-orbit.jpg',
    bpm: 76,
    musicalKey: 'D min',
    x: 28,
    y: 66,
    offline: false,
    verified: true,
    sizeMb: 36.4,
  },
  {
    id: 9,
    title: 'Paper Moon Radio',
    artist: 'Common Field',
    album: 'Open Late',
    duration: '3:54',
    durationSeconds: 234,
    source: '酷我',
    quality: 'FLAC 24/44.1',
    cover: '/covers/glass-hours.jpg',
    bpm: 118,
    musicalKey: 'A maj',
    x: 42,
    y: 39,
    offline: false,
    verified: true,
    sizeMb: 47.8,
  },
  {
    id: 10,
    title: 'Low Tide Cinema',
    artist: 'June Echo',
    album: 'After Midnight',
    duration: '5:06',
    durationSeconds: 306,
    source: '酷狗',
    quality: 'FLAC 24/96',
    cover: '/covers/home-dawn.jpg',
    bpm: 88,
    musicalKey: 'C min',
    x: 58,
    y: 54,
    offline: false,
    verified: true,
    sizeMb: 88.6,
  },
  {
    id: 11,
    title: 'Still Moving',
    artist: 'North Assembly',
    album: 'Afterimage',
    duration: '3:27',
    durationSeconds: 207,
    source: 'QQ',
    quality: 'FLAC 16/44.1',
    cover: '/covers/second-wind.jpg',
    bpm: 126,
    musicalKey: 'E maj',
    x: 73,
    y: 28,
    offline: false,
    verified: true,
    sizeMb: 29.7,
  },
  {
    id: 12,
    title: 'Violet Transit',
    artist: 'Lena Shore',
    album: 'Night Current',
    duration: '4:18',
    durationSeconds: 258,
    source: '网易云',
    quality: 'FLAC 24/48',
    cover: '/covers/blue-static.jpg',
    bpm: 121,
    musicalKey: 'F maj',
    x: 88,
    y: 22,
    offline: false,
    verified: true,
    sizeMb: 54.1,
  },
]

export const memoryNodes: MemoryNode[] = [
  { id: 'late-focus', label: '深夜专注', detail: '38 次播放', x: 47, y: 42, weight: 5, tone: 'acid' },
  { id: 'female-vocal', label: '清澈女声', detail: '偏好 +27%', x: 67, y: 27, weight: 3, tone: 'coral' },
  { id: 'city-pop', label: '城市律动', detail: '92-118 BPM', x: 72, y: 62, weight: 4, tone: 'blue' },
  { id: 'piano', label: '极简钢琴', detail: '周日夜间', x: 26, y: 28, weight: 3, tone: 'white' },
  { id: 'ambient', label: '无鼓氛围', detail: '低能量入口', x: 19, y: 68, weight: 2, tone: 'blue' },
  { id: 'live', label: '现场空间', detail: '新偏好', x: 83, y: 43, weight: 2, tone: 'white' },
  { id: 'instrumental', label: '器乐叙事', detail: '连续 23 天', x: 45, y: 75, weight: 3, tone: 'coral' },
]

export const initialAgentEvents: AgentEvent[] = [
  { id: 1, label: '选曲完成', detail: '已从 18 个结果中选出 6 首', state: 'done' },
  { id: 2, label: '音质检查完成', detail: '4 首歌曲提供无损版本', state: 'done' },
  { id: 3, label: '正在优化顺序', detail: '根据节奏与调性调整衔接', state: 'active' },
  { id: 4, label: '等待下载', detail: '确认后保存到本机', state: 'waiting' },
]
